deployment_id_label_order:
  - namespace
  - network_name
  - provider
  - region
  - stack
  - deployment_id

registration_id_label_order:
  - namespace
  - network_name
  - provider
  - region

remote_state_path_label_order:
  - namespace
  - stack
  - provider
  - network_name
  - region
  - deployment_id

registration_remote_state_path_label_order:
  - namespace
  - network_name
  - provider
  - region

dns_order:
  - region
  - provider
  - network_name
  - namespace

id_label_order:
  - namespace
  - stack
  - network_name

short_id_label_order:
  - stack

name_label_order:
  - namespace
  - stack
  - network_name
