#---
## Script to set secrets profiles.
##
## - Secrets profiles exist in secrets.yml files at the root
## - They have several fields that have keys that produce a list of profiles.
## - These profiles all have a `name` that is the id of the profile that is looked when applying or destroying.
#
#profiles_intro_:
#  type: print
#  statement: Configuring SSH and wallet profiles
#
#choice_:
#  type: checkbox
#  message: Which profiles would you like to set?
#  choices:
#    - docs: Open docs to explain this
#    - ssh: SSH keys
#    - wallet: Wallets / keystores
##    - cloud: Cloud credentials
#
#docs:
#  type: webbrowser
#  url: https://www.notion.so/insightx/Introductory-Tutorials-0416f96a30ee485f9e30c3a75b4910bf
#  when: "{{ 'docs' in profiles.choice_ }}"
#
#run_choice_:
#  type: nukikata
#  loop: "{{ profiles.choice_ }}"
#  context_file: "{{ profiles.item }}"
#  existing_context: "{{ profiles }}"
#  when: "{{ profiles.item != 'docs' }}"
#