---
# Settings that are consistent across the project

_environments:
  - dev
  - test
  - stage
  - prod

_network_choices:
  - mainnet: Mainnet
  - pagoda: Pagoda - TestNet for PReps
  - euljiro: Euljiro - Testnet for Exchanges
  - yeouido: Yeouido - Testnet for DApps

_network_files:
  - mainnet: Mainnet
  - zicon: Zicon / Pagoda - TestNet for PReps
  - bicon: Bicon / Euljiro - Testnet for Exchanges
  - testnet: Testnet / Yeouido - Testnet for DApps

deployments_list_:
  type: listdir
  path: deployments
  ignore_hidden_files: true

deployments_dir_:
  type: find_in_parent
  target: deployments

registrations_list_:
  type: listdir
  path: registrations
  ignore_hidden_files: true

registration_dir_:
  type: find_in_parent
  target: registrations

scripts_dir_:
  type: find_in_parent
  target: scripts

secrets_file_:
  type: find_in_parent
  target: secrets.yml
  fallback: NotExist

secrets_file_write_:
  type: yaml
  path: secrets.yml
  when: "{{ settings.secrets_file_ == 'NotExist' }}"
  contents:
    cloud_profiles:
      aws: []
      azure: []
      do: []
      gcp: []
    ssh_profiles: []
    wallet_profiles: []
  
settings_:
  type: yaml
  path: settings.yml

# Always called from root
base_directory_:
  type: stat
  input: "{{ cwd }}"
  
run_file_:
  type: stat
  input: "{{ cwd }}/run.yml"
